[tool.poetry]
name = "ai-ollama-pdf-qa"
version = "0.1.0"
description = ""
authors = ["William <will.downing00@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
langchain = "0.0.21"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
